### PR TITLE
remove esmeefairbairn

### PR DESCRIPTION
**Pull request by matkoniecz**
does not appear to be viable funding source for OS based on what the want to fund

### CODE REVIEW

**Comment by matkoniecz** [comment]
based on https://esmeefairbairn.org.uk/our-support/funding-plus/applying-funding-plus/

**Comment by ralphtheninja** [comment]
@matkoniecz Maybe rebase the latest PRs since we merged the changes where the single letter sections were removed?

**Comment by matkoniecz** [comment]
Why? It still merge cleanly. And you can use "rebase and merge" mode, see drop-down on merge button.

**Comment by RichardLitt** [comment]
Yep. I think this is fine. Thanks.

**Pull request merged**
