### PR TITLE
"Siegel (...) does not currently accept unsolicited proposals."

### PR DESCRIPTION
**Pull request by matkoniecz**
> Please note that Siegel Family Endowment does not currently accept unsolicited proposals.

https://www.siegelendowment.org/contact/

### CODE REVIEW

**Comment by RichardLitt** [comment]
That doesn't mean it isn't open, just that you need to contact them first with your idea.

**Comment by matkoniecz** [comment]
I understood that "contact them first with your idea." is exactly "unsolicited proposal".

**Comment by RichardLitt** [comment]
I understood that it was "we don't take new proposals without talking to us, so use this form first"....

**Comment by matkoniecz** [comment]
I got no reply from them

**Comment by RichardLitt** [comment]
Thanks for checking! Merged.

**Pull request merged**
