### PR TITLE
remove Grant for the Web

### PR DESCRIPTION
**Pull request by matkoniecz**
"Our last open call ended in September 2021." and link died and their website has no indication of program existing

### CODE REVIEW

**Comment by RichardLitt** [comment]
This one still seems open? https://interledger.org/ambassadors

**Comment by matkoniecz** [comment]
> 6-month project that advances the digital financial inclusion agenda specific to their expertise and networks. This program is ideal for researchers, developers, open-source contributors, entrepreneurs, educators, policy regulators, open standards enthusiasts, digital and financial rights advocates, creators, and artists operating at the intersection of technology and community. All ambassadors will receive a $30,000 grant for research, building, organizing, and advocacy.

I guess it fits? It sounds like it will demand use of specifically their tech and is less open that it describes itself but the same fits many this private fiat money projects.

**Comment by RichardLitt** [comment]
It's not ideal, but might be useful to someone. I ignored their more "integrate with our stuff" grants...

**Comment by matkoniecz** [comment]
I wonder about maybe having separate list for more narrow funding of "play with our stuff" variety where say "develop this private fiat money project" would go.

**Comment by RichardLitt** [comment]
It might make the list of more freely-associated grants really small...

**Comment by matkoniecz** [comment]
I guess the problem is that it is hard to define line between "we are outsourcing development for our get-rich-quick-scheme" and "we are interested in this useful well defined area"

**Pull request closed without merging**
