### PR TITLE
Remove some defunct or unavailable

### PR DESCRIPTION
**Pull request by matkoniecz**
[Aspen Tech Policy Hub - died during COVID](https://github.com/ralphtheninja/open-funding/commit/759d17a61abd1039f4af1289538ac554a8fa4f7b)

[remove Wau Holland Stiftung](https://github.com/ralphtheninja/open-funding/commit/93e29a9356a5096e1a0895857c925745b1d0d9e2) - no indicator that you can apply for funding

[remove World Wide Web Foundation](https://github.com/ralphtheninja/open-funding/commit/171f631877cfa86805e349537b6450250028c307) - no link to any funding in current file, no obvious grant opportunities at their page

[remove List of all the funds published on OpenCollective](https://github.com/ralphtheninja/open-funding/commit/fdbe62f7f801f1081c1cb7a4afbb4e4076f1941b) - no direct funding opportunities, nearly all or all of this funds do not accept or invite funding requests

[remove Mozila Ventures](https://github.com/ralphtheninja/open-funding/commit/a25157004bf171f25103f6e49d00a387c19b58d8) - no funding opportunity available

### CODE REVIEW

**Comment by matkoniecz** [comment]
maybe it would be better to split such PR into parts. Each going as own PR with TOC regen done from time to time?

**Comment by ralphtheninja** [comment]
> maybe it would be better to split such PR into parts. Each going as own PR with TOC regen done from time to time?

Aye, I think it's ok if the TOC isn't completely up to date as we remove and change things. This will stabilize in a while and then we can be more careful with keeping the TOC fresh.

**Comment by matkoniecz** [comment]
Seems to still merge after #78

**Comment by RichardLitt** [comment]
Thanks.

**Pull request merged**
