### PR TITLE
refactor: Remove empty letter headers

### PR DESCRIPTION
**Pull request by RichardLitt**
Not needed. See https://github.com/ralphtheninja/open-funding/pull/68\#discussion_r1738555977.

### CODE REVIEW

**Comment by matkoniecz** [comment]
hmm, potential benefit is that if new entry appears for one of this letters it is not needed to create them manually

not convinced either way

**Comment by RichardLitt** [comment]
I'm not convinced we need the alphabetic headers at all. What do they add?

**Comment by matkoniecz** [comment]
good point

I would support altogether removing them

**Comment by ralphtheninja** [comment]
Sounds good. Kill it :fire: :smile:

**Comment by RichardLitt** [comment]
Pushed.

**Pull request merged**
