### PR TITLE
update Interledger

### PR DESCRIPTION
**Pull request by matkoniecz**
replaces #70

### CODE REVIEW

**Comment by matkoniecz** [comment]
how can I regenerate TOC?

**Comment by ralphtheninja** [comment]
> how can I regenerate TOC?

`npm i && npm run toc`

**Comment by ralphtheninja** [comment]
I squashed some of the PRs so you might want to rebase this one before generating the toc.

**Comment by matkoniecz** [comment]
regenerated TOC here, have not done in the other PR to avoid conflicts

**Pull request merged**
